---
name: format

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Grab source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install tooling
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure
